replicaCount: 1

image:
  repository: 799121415609.dkr.ecr.eu-central-1.amazonaws.com/niceye-hrportal
  pullPolicy: IfNotPresent
  tag: "93d372e"  # This gets replaced by buildspec.yml

env:
  NODE_ENV: production
  PORT: "3000"
  TZ: Europe/Istanbul
  DATABASE_URL: "postgresql://niceye-hrportal:Kjcv45u*BnCn*t@postgres-shared-rw.cnpg.svc.cluster.local:5432/niceye-hrportal"
  NEXTAUTH_SECRET: "e0cfaf30eb2540a179b5d2486234059f20feb827158467ea6735156e2ba08b94"
  NEXTAUTH_URL: "https://hrportal.niceye.com"
  AZURE_AD_CLIENT_ID: "TODO-DEVOPS-SET-AZURE-AD-CLIENT-ID"
  AZURE_AD_CLIENT_SECRET: "TODO-DEVOPS-SET-AZURE-AD-CLIENT-SECRET"
  AZURE_AD_TENANT_ID: "TODO-DEVOPS-SET-AZURE-AD-TENANT-ID"
  SMTP_HOST: "TODO-DEVOPS-SET-SMTP"
  SMTP_PORT: "587"
  SMTP_USER: "TODO-DEVOPS-SET-USER"
  SMTP_PASS: "TODO-DEVOPS-SET-PASS"
  SMTP_FROM: "noreply@niceye.com"

service:
  type: NodePort
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  hosts:
    - host: hrportal.niceye.com
      paths:
        - path: /
          pathType: Prefix
  tls:
  - secretName: hrportal.niceye.com
    hosts:
    - hrportal.niceye.com

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 20m
    memory: 256Mi

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false

persistence:
  enabled: true
  size: 5Gi
  storageClassName: "gp3"
